# Generated by Django 3.0.2 on 2020-01-15 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField(verbose_name='ID класса')),
                ('class_title', models.CharField(default='', max_length=300, verbose_name='Название класса')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.IntegerField(verbose_name='ID стихии')),
                ('element_title', models.CharField(default='', max_length=300, verbose_name='Название стихии')),
            ],
            options={
                'verbose_name': 'Стихия',
                'verbose_name_plural': 'Стихии',
            },
        ),
        migrations.CreateModel(
            name='Reasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_id', models.IntegerField(verbose_name='ID')),
                ('reason_title', models.CharField(default='', max_length=300, verbose_name='Наименование причины')),
            ],
            options={
                'verbose_name': 'Причина отсутсвия',
                'verbose_name_plural': 'причины отсутсвтвия',
            },
        ),
        migrations.CreateModel(
            name='StatusAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField(verbose_name='Номер статуса')),
                ('status_title', models.CharField(default='', max_length=300, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус для администрирования',
                'verbose_name_plural': 'Статусы для администрирования',
            },
        ),
        migrations.CreateModel(
            name='StatusBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField(verbose_name='Номер статуса')),
                ('status_title', models.CharField(default='', max_length=300, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус для телеграм',
                'verbose_name_plural': 'Статусы для телеграм',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField(verbose_name='ID')),
                ('subject_title', models.CharField(default='', max_length=300, verbose_name='Наименование причины')),
            ],
            options={
                'verbose_name': 'Предметы',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_id', models.CharField(max_length=300, unique=True, verbose_name='EDU_ID')),
                ('telegram_id', models.CharField(default='', max_length=300, verbose_name='Телеграм')),
                ('surname', models.CharField(max_length=300, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('admin_status', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='edu_tatar.StatusAdmin', verbose_name='Статус для администрирования')),
                ('class_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='edu_tatar.Classes', verbose_name='Статус для бота')),
                ('element_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='edu_tatar.Elements', verbose_name='Стихия')),
                ('status_bot', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='edu_tatar.StatusBot', verbose_name='Статус для бота')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_id', models.CharField(max_length=300, unique=True, verbose_name='EDU_ID')),
                ('telegram_id', models.CharField(default='', max_length=300, verbose_name='Телеграм')),
                ('surname', models.CharField(max_length=300, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('admin_status', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='edu_tatar.StatusAdmin', verbose_name='Статус для администрирования')),
                ('class_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='edu_tatar.Classes', verbose_name='Статус для бота')),
                ('element_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='edu_tatar.Elements', verbose_name='Стихия')),
                ('status_bot', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='edu_tatar.StatusBot', verbose_name='Статус для бота')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default='', verbose_name='Оценка')),
                ('mark_date', models.DateField(verbose_name='Дата получения')),
                ('state', models.CharField(default='', max_length=200, verbose_name='Вид работы')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_tatar.Classes', verbose_name='Класс')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_tatar.Subjects', verbose_name='Предмет')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_tatar.Students', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='ClassAbsent',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество отсутсвующих')),
                ('date', models.DateField(verbose_name='Дата')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_tatar.Classes', verbose_name='ID класса')),
            ],
            options={
                'verbose_name': 'По классам',
                'verbose_name_plural': 'По классам',
            },
        ),
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('reason_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_tatar.Reasons', verbose_name='Причина отсутствия')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_tatar.Students', verbose_name='ID ученика')),
            ],
            options={
                'verbose_name': 'Отсутвующие',
                'verbose_name_plural': 'Отсутвующие',
            },
        ),
    ]
